package com.server.zoho.workflow.model;

public enum BuildProductStatus
{

	PENDING("PENDING"),
	BUILD_STARTED("BUILD_STARTED"),
	BUILD_SUCCESS("BUILD_SUCCESS"),
	BUILD_FAILED("BUILD_FAILED"),
	CHANNEL_MAPPED("CHANNEL_MAPPED"),
	CHANNEL_MAPPING_FAILED("CHANNEL_MAPPING_FAILED"),
	MILESTONE_CREATED("MILESTONE_CREATED"),
	MILESTONE_FAILED("MILESTONE_FAILED"),
	SD_CSEZ_BUILD_UPLOADED("SD_CSEZ_BUILD_UPLOADED"),
	SD_CSEZ_BUILD_UPLOAD_FAILED("SD_CSEZ_BUILD_UPLOAD_FAILED"),
	SD_LOCAL_BUILD_UPLOADED("SD_LOCAL_BUILD_UPLOADED"),
	SD_LOCAL_BUILD_UPLOAD_FAILED("SD_LOCAL_BUILD_UPLOAD_FAILED"),
	SD_PRE_BUILD_UPLOADED("SD_PRE_BUILD_UPLOADED"),
	SD_PRE_BUILD_UPLOAD_FAILED("SD_PRE_BUILD_UPLOAD_FAILED"),
	CANCELLED("CANCELLED");

	private String name;

	BuildProductStatus(String name)
	{
		this.name = name;
	}

	public String getName()
	{
		return name;
	}
}
